version: "3.7"

services:
    # image project
    app:
        build:
            args:
                user: ${APP_USER}
                uid: ${APP_UID}
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - phpcomposer

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8005:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - phpcomposer

    # db mysql
    # db:
    #     image: mysql:5.7.22
    #     platform: linux/x86_64
    #     restart: unless-stopped
    #     environment:
    #         MYSQL_DATABASE: ${DB_DATABASE:-laravel}
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    #         MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
    #         MYSQL_USER: ${DB_USERNAME:-username}
    #     volumes:
    #         - ./.docker/mysql/dbdata:/var/lib/mysql
    #     ports:
    #         - "3388:3306"
    #     networks:
    #         - phpcomposer

    # queue
    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - phpcomposer

    # redis
    redis:
        image: redis:latest
        networks:
            - phpcomposer

networks:
    phpcomposer:
        driver: bridge
